import type { Era } from './data/timeline-data'
import { colorForProgress } from './data/timeline-data'

/**
 * Generate a shareable progress snapshot as a PNG image.
 * Uses Canvas 2D — no external dependencies.
 */
export function exportProgressImage(
  eras: Era[],
  progress: Record<string, number>,
  packName: string,
  streakDays: number,
): void {
  const CARD_W = 800
  const ROW_H = 36
  const HEADER_H = 100
  const FOOTER_H = 60
  const PADDING = 24
  const BAR_H = 16

  // Group eras
  const grouped = Object.entries(
    eras.reduce<Record<string, Era[]>>((acc, era) => {
      acc[era.group] = [...(acc[era.group] ?? []), era]
      return acc
    }, {}),
  )

  // Calculate total height
  const groupHeaderH = 32
  const totalEraRows = eras.length
  const totalGroupHeaders = grouped.length
  const CARD_H = HEADER_H + FOOTER_H + (totalEraRows * ROW_H) + (totalGroupHeaders * groupHeaderH) + PADDING * 2

  const canvas = document.createElement('canvas')
  canvas.width = CARD_W * 2  // 2x for retina
  canvas.height = CARD_H * 2
  const ctx = canvas.getContext('2d')
  if (!ctx) return

  ctx.scale(2, 2)

  // Background
  ctx.fillStyle = '#0f172a'
  ctx.beginPath()
  roundRect(ctx, 0, 0, CARD_W, CARD_H, 16)
  ctx.fill()

  // Header gradient
  const headerGrad = ctx.createLinearGradient(0, 0, CARD_W, 0)
  headerGrad.addColorStop(0, '#0f172a')
  headerGrad.addColorStop(0.5, '#083344')
  headerGrad.addColorStop(1, '#0f172a')
  ctx.fillStyle = headerGrad
  ctx.fillRect(0, 0, CARD_W, HEADER_H)

  // Title
  ctx.fillStyle = '#e2e8f0'
  ctx.font = 'bold 22px Inter, system-ui, sans-serif'
  ctx.fillText('Parallax Atlas', PADDING, 36)

  // Pack name + date
  ctx.fillStyle = '#94a3b8'
  ctx.font = '14px Inter, system-ui, sans-serif'
  ctx.fillText(`${packName} · ${new Date().toLocaleDateString()}`, PADDING, 58)

  // Summary stats
  const values = eras.map((e) => progress[e.id] ?? 0)
  const avg = values.length ? Math.round(values.reduce((s, v) => s + v, 0) / values.length) : 0
  const mastered = values.filter((v) => v >= 100).length
  const started = values.filter((v) => v > 0).length

  ctx.fillStyle = '#22d3ee'
  ctx.font = 'bold 14px Inter, system-ui, sans-serif'
  const statsText = `Avg ${avg}% · ${started}/${eras.length} started · ${mastered} mastered${streakDays > 0 ? ` · 🔥 ${streakDays}d streak` : ''}`
  ctx.fillText(statsText, PADDING, 82)

  // Divider
  ctx.strokeStyle = '#1e293b'
  ctx.lineWidth = 1
  ctx.beginPath()
  ctx.moveTo(PADDING, HEADER_H - 4)
  ctx.lineTo(CARD_W - PADDING, HEADER_H - 4)
  ctx.stroke()

  // Era rows
  let y = HEADER_H + PADDING

  for (const [group, groupEras] of grouped) {
    // Group header
    ctx.fillStyle = '#64748b'
    ctx.font = 'bold 11px Inter, system-ui, sans-serif'
    ctx.fillText(group.toUpperCase(), PADDING, y + 12)
    y += groupHeaderH

    for (const era of groupEras) {
      const value = progress[era.id] ?? 0

      // Era name
      ctx.fillStyle = '#cbd5e1'
      ctx.font = '13px Inter, system-ui, sans-serif'
      const nameMaxWidth = CARD_W * 0.45
      const truncatedName = truncateText(ctx, era.content, nameMaxWidth)
      ctx.fillText(truncatedName, PADDING, y + 14)

      // Progress bar background
      const barX = CARD_W * 0.52
      const barW = CARD_W - barX - PADDING - 60
      ctx.fillStyle = '#1e293b'
      roundRect(ctx, barX, y + 4, barW, BAR_H, 4)
      ctx.fill()

      // Progress bar fill
      if (value > 0) {
        const fillW = Math.max(4, (barW * value) / 100)
        ctx.fillStyle = colorForProgress(value)
        roundRect(ctx, barX, y + 4, fillW, BAR_H, 4)
        ctx.fill()
      }

      // Percentage
      ctx.fillStyle = value >= 100 ? '#fbbf24' : '#94a3b8'
      ctx.font = 'bold 12px Inter, system-ui, sans-serif'
      ctx.textAlign = 'right'
      ctx.fillText(`${value}%`, CARD_W - PADDING, y + 16)
      ctx.textAlign = 'left'

      y += ROW_H
    }
  }

  // Footer
  ctx.fillStyle = '#334155'
  ctx.font = '11px Inter, system-ui, sans-serif'
  ctx.fillText('Generated by Parallax Atlas · parallax-atlas.app', PADDING, CARD_H - 20)

  // Download
  canvas.toBlob((blob) => {
    if (!blob) return
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `parallax-atlas-progress-${Date.now()}.png`
    link.click()
    URL.revokeObjectURL(url)
  }, 'image/png')
}

/** Draw a rounded rectangle path (no fill/stroke) */
function roundRect(ctx: CanvasRenderingContext2D, x: number, y: number, w: number, h: number, r: number): void {
  ctx.beginPath()
  ctx.moveTo(x + r, y)
  ctx.lineTo(x + w - r, y)
  ctx.quadraticCurveTo(x + w, y, x + w, y + r)
  ctx.lineTo(x + w, y + h - r)
  ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h)
  ctx.lineTo(x + r, y + h)
  ctx.quadraticCurveTo(x, y + h, x, y + h - r)
  ctx.lineTo(x, y + r)
  ctx.quadraticCurveTo(x, y, x + r, y)
  ctx.closePath()
}

/** Truncate text with ellipsis to fit within maxWidth */
function truncateText(ctx: CanvasRenderingContext2D, text: string, maxWidth: number): string {
  if (ctx.measureText(text).width <= maxWidth) return text
  let truncated = text
  while (truncated.length > 0 && ctx.measureText(truncated + '…').width > maxWidth) {
    truncated = truncated.slice(0, -1)
  }
  return truncated + '…'
}
